version: '3'

output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

includes:
  infra: ./tasks/Taskfile.infra.yml
  audit: ./tasks/Taskfile.audit.yml
  report: ./tasks/Taskfile.report.yml
  scan-compliance: ./tasks/Taskfile.scan-compliance.yml
vars:
  DEFAULT_IMAGE: "ghcr.io/taha2samy/wolfi-openssl-fips:3.5.5-distroless"
  STANDARD_IMAGE: "ghcr.io/taha2samy/wolfi-openssl-fips:3.5.5"
  RESULTS_ROOT: "allure-results"
  REPORT_DIR: "allure-report"
  repo_of_registry: "wolfi-openssl-fips"
  owner: "taha2samy"
  registry: "ghcr.io"
  repo_of_code: "openssl_fips"
  repo_url: "https://github.com/{{.owner}}/{{.repo_of_code}}"

tasks:
  echo-all-vars:
    desc: Display all project-related global variables
    cmds:
      - echo "repo_of_registry {{.repo_of_registry}}"
      - echo "owner            {{.owner}}"
      - echo "registry         {{.registry}}"
      - echo "repo_of_code     {{.repo_of_code}}"
      - echo "repo_url         {{.repo_url}}"

  setup:
    desc: Prepare the infrastructure by building all Docker bridge images
    cmds:
      - task: infra:build-all

  run-v2:
    desc: Execute full audit pipeline and serve via Allure 2
    cmds:
      - task: audit:run
      - task: report:v2:serve

  run-v3:
    desc: Execute full audit pipeline and serve via Allure 3
    cmds:
      - task: audit:run
      - task: report:v3:serve

  clean-all:
    desc: Cleanup all images, test results, and generated reports
    cmds:
      - task: audit:clean
      - task: report:clean
      - task: infra:clean

  update-pkgs:
  
    desc: Run the python package updater script
    cmds:
      - chmod +x scripts/wolfi-pkg-updater.py
      - python scripts/wolfi-pkg-updater.py
  docs:generate_benchmark_data:
    desc: Run performance benchmarks
    dir: benchmark
    cmds:
      - chmod +x ./run_benchmark.sh
      - ./run_benchmark.sh

  docs:parse_benchmark_data:
    desc: Parse benchmark results
    cmds:
      - pipenv run python benchmark/parser.py
      - pipenv run python benchmark/parser_signatures.py


  docs:generate_readme:
      desc: Generates the README.md file
      cmds:
        - pipenv run python scripts/update_readme.py


  convert-ver-to-sha_action_of_github:
    desc: convert version of github action versions to sh265
    cmds:
      - pipenv run python scripts/github_action_ver_to_sha.py 

  docs:serve:
    desc: "Run MkDocs server locally for live preview"
    cmds:
      - pipenv run mkdocs serve --dev-addr 0.0.0.0:8000
  

  docs:build-MkDocs-site:
      desc: "Build the final FIPS Boundary Security Dashboard"
      summary: |
        This task generates the static site (MkDocs).
        It assumes all JSON reports (Trivy, KICS, Benchmarks) 
        are already gathered in the 'reports/' folder.
      cmds:
        - echo "Building MkDocs Security Dashboard..."
        - pipenv run mkdocs build --clean
        - echo "Done! The site is ready in the 'site/' directory."
  gh:upload-sbom:
      internal: true
      cmds:
        - python3 scripts/upload_sbom.py {{.FILE}} {{.TARGET}} {{.REPO}}
      vars:
        FILE: '{{default "" .FILE}}'
        TARGET: '{{default "" .TARGET}}'
        REPO: '{{default "" .REPO}}'