version: '3'

output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

includes:
  infra: ./tasks/Taskfile.infra.yml
  audit: ./tasks/Taskfile.audit.yml
  report: ./tasks/Taskfile.report.yml
  scan-compliance: ./tasks/Taskfile.scan-compliance.yml
  docs: ./tasks/Taskfile.doc.yml
  gh: ./tasks/Taskfile.github.yml

vars:
  FIPS_VERSION: "3.1.2"
  CORE_VERSION: "3.5.5"
  owner: "taha2samy"
  registry: "ghcr.io"
  repo_of_registry: "wolfi-openssl-fips"
  repo_of_code: "openssl_fips"
  repo_url: "https://github.com/{{.owner}}/{{.repo_of_code}}"
  DISTROLESS_IMAGE: "{{.registry}}/{{.owner}}/{{.repo_of_registry}}:{{.CORE_VERSION}}-distroless"
  STANDARD_IMAGE: "{{.registry}}/{{.owner}}/{{.repo_of_registry}}:{{.CORE_VERSION}}"
  DEV_IMAGE: "{{.registry}}/{{.owner}}/{{.repo_of_registry}}:{{.CORE_VERSION}}-dev"
  RESULTS_ROOT: "reports"
  REPORT_DIR: "reports"
  RESULTS_REPORT: "reports"
tasks:
  echo-all-vars:
    desc: Display all project-related global variables
    cmds:
      - echo "repo_of_registry {{.repo_of_registry}}"
      - echo "owner            {{.owner}}"
      - echo "registry         {{.registry}}"
      - echo "repo_of_code     {{.repo_of_code}}"
      - echo "repo_url         {{.repo_url}}"

  setup:
    desc: Prepare the infrastructure by building all Docker bridge images
    cmds:
      - task: infra:build-all

  run-v2:
    desc: Execute full audit pipeline and serve via Allure 2
    cmds:
      - task: audit:run
      - task: report:v2:serve

  run-v3:
    desc: Execute full audit pipeline and serve via Allure 3
    cmds:
      - task: audit:run
      - task: report:v3:serve

  clean-all:
    desc: Cleanup all images, test results, and generated reports
    cmds:
      - task: audit:clean
      - task: report:clean
      - task: infra:clean

  update-pkgs:
    desc: Run the python package updater script
    cmds:
      - chmod +x scripts/wolfi-pkg-updater.py
      - python scripts/wolfi-pkg-updater.py


  convert-ver-to-sha_action_of_github:
    desc: convert version of github action versions to sh265
    cmds:
      - pipenv run python scripts/github_action_ver_to_sha.py 

