
version: '3'

tasks:
  update-versions:
    cmds:
      - cmd: chmod +x scripts/wolfi-pkg-updater.py
      - cmd: scripts/wolfi-pkg-updater.py
  benchmark:
    dir: benchmark
    cmds:
      - cmd: chmod +x run_benchmarks.sh
      - cmd: ./run_benchmarks.sh
  generate-report:
    dir: benchmark
    cmds:
      - cmd: chmod +x generate_report.py
      - cmd: ./generate_report.py
