version: '3'

vars:
  IMAGE_NAME: openssl-fips:wolfi
  ARCH:
    sh: uname -m | sed -e 's/x86_64/linux\/amd64/' -e 's/aarch64/linux\/arm64/'

tasks:
  default:
    cmds:
      - task: build
      - task: test

  build:
    desc: Build the Docker image locally
    cmds:
      - docker buildx build --load --platform {{.ARCH}} -t {{.IMAGE_NAME}} .

  test:
    desc: Run all FIPS verification tests
    deps: [build]
    cmds:
      - task: check-providers
      - task: check-config
      - task: verify-sha256
      - task: verify-md5-fail

  check-providers:
    cmds:
      - echo "--- [1/4] Verifying FIPS Provider Status ---"
      - docker run --rm {{.IMAGE_NAME}} list -provider fips

  check-config:
    cmds:
      - echo "--- [2/4] Verifying FIPS Module Configuration ---"
      - docker run --rm --entrypoint cat {{.IMAGE_NAME}} /usr/local/ssl/fipsmodule.cnf

  verify-sha256:
    cmds:
      - echo "--- [3/4] Testing Allowed Algorithm (SHA256) ---"
      - echo "test" | docker run -i --rm {{.IMAGE_NAME}} sha256 -provider fips -propquery fips=yes

  verify-md5-fail:
    cmds:
      - echo "--- [4/4] Testing Forbidden Algorithm (MD5) ---"
      - |
        if docker run --rm {{.IMAGE_NAME}} md5 -provider fips -propquery fips=yes 2>/dev/null; then
          echo "FAILED: MD5 should not be allowed in FIPS mode"; exit 1;
        else
          echo "PASSED: MD5 was correctly blocked"; exit 0;
        fi

  clean:
    desc: Remove local image
    cmds:
      - docker rmi {{.IMAGE_NAME}} || true
  update-digest:
    desc: Check upstream Wolfi image and update variables.hcl if changed
    cmds:
      - |
        echo "Checking latest digest for {{.TARGET_IMAGE}}..."
        
        # Fetch latest SHA256 digest using crane (no docker pull required)
        LATEST_DIGEST=$(docker run --rm {{.CRANE_IMAGE}} digest {{.TARGET_IMAGE}})
        
        # Extract current digest from variables.hcl
        CURRENT_DIGEST=$(grep -oP '(?<=default = ").*sha256:.*(?=")' {{.HCL_FILE}})
        
        echo "Current: $CURRENT_DIGEST"
        echo "Latest:  $LATEST_DIGEST"
        
        if [ "$CURRENT_DIGEST" != "$LATEST_DIGEST" ]; then
          echo "Updates found. Applying changes..."
          # Update the file using sed
          sed -i "s|$CURRENT_DIGEST|$LATEST_DIGEST|" {{.HCL_FILE}}
          echo "variables.hcl updated successfully."
        else
          echo "Image is up to date. No changes made."
        fi
